# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Thanh/Desktop/OV7670_With_VGA/HC_SR04/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Thanh/Desktop/OV7670_With_VGA/HC_SR04/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Thanh/Desktop/OV7670_With_VGA/HC_SR04/project_1/project_1.srcs/sources_1/imports/new/BCD_converter.v
  C:/Users/Thanh/Desktop/OV7670_With_VGA/HC_SR04/project_1/project_1.srcs/sources_1/new/HC_SR04_interface.v
  C:/Users/Thanh/Desktop/OV7670_With_VGA/HC_SR04/project_1/project_1.srcs/sources_1/imports/sources_1/debounce.v
  C:/Users/Thanh/Desktop/OV7670_With_VGA/HC_SR04/project_1/project_1.srcs/sources_1/imports/sources_1/sevensegment.v
  C:/Users/Thanh/Desktop/OV7670_With_VGA/HC_SR04/project_1/project_1.srcs/sources_1/new/Nexys4_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Thanh/Desktop/OV7670_With_VGA/HC_SR04/project_1/project_1.srcs/constrs_1/imports/project1_release/n4DDRfpga_withvideo.xdc
set_property used_in_implementation false [get_files C:/Users/Thanh/Desktop/OV7670_With_VGA/HC_SR04/project_1/project_1.srcs/constrs_1/imports/project1_release/n4DDRfpga_withvideo.xdc]


synth_design -top Nexys4_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Nexys4_top.dcp

catch { report_utilization -file Nexys4_top_utilization_synth.rpt -pb Nexys4_top_utilization_synth.pb }
